services:
  database:
    image: dexels/dvdrental:latest
    container_name: dvdrental-container
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dvdrental
      POSTGRES_PASSWORD: tbs666V
  app-rest:
    build:
      context: .
      dockerfile: /Dockerfile
    ports:
      - 8080:8080
